# Kitty terminal. Theme "Amphora".
font_family      JetBrainsMono Nerd Font
font_size        11.5
shell            zsh

background_opacity 0.88
window_padding_width 10
confirm_os_window_close 0
enable_audio_bell no
cursor_shape beam

include amphora.conf
